### ISSUE TITLE
cannot find package "yottachain/ytfs-util"

### ISSUE THREAD

**Issue by DoMyJob** [yottachain/P2PHost#2]
../../../P2PHost/host.go:8:2: cannot find package "yottachain/ytfs-util" in any of:
	/usr/local/Cellar/go/1.12.3/libexec/src/yottachain/ytfs-util (from $GOROOT)
	/Users/yueawang/works/go/src/yottachain/ytfs-util (from $GOPATH)

**Comment by dp1993132** [comment]
我将util挪到了p2phost目录
